
trigger:
- main

resources:
- repo: self
pool: default

variables:
  tag: v1
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
   
      

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub-registry'
        repository: 'jksoam777/jkelearn'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
   
     
    