trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker build -t myapp:v1 .
      docker tag myapp:v1 jkacr1.azurecr.io/myapp:v1
      docker push jkacr1.azurecr.io/myapp:v1
