trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout your code
- checkout: self

# Step 2: Install Node.js
- task: UseNode@1
  inputs:
    version: '18.x'

# Step 3: Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Step 4: Prepare SonarQube analysis
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'varun'
    cliProjectName: 'varun'
    cliSources: '.'
    extraProperties: |
      sonar.projectVersion=1.0
      # Don't use branch name to avoid Community Edition limitation
      sonar.branch.name=

# Step 5: Run Sonar Scanner (React/JS uses CLI scanner)
- script: |
    npx sonar-scanner
  displayName: 'Run Sonar Scanner'

# Step 6: Publish results
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
