# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self
pool: default

variables:
  tag: v1
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
   
      

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub-registry'
        repository: 'jksoam777/frantnew1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'service-jk'
        azureResourceGroup: 'jksoam'
        kubernetesCluster: 'jkculster'
        manifests: 'Manifests'