name: frantend
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 
    jobs:
      - job:
        steps:
        - task: Npm@1
          inputs:
            command: 'install'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'npm run build'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
            ArtifactName: 'NPM-ARC'
            publishLocation: 'Container'
        


     