# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: 'install'
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'cli'
    configMode: 'file'
- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'


