trigger:
 branches:
    include:
      - main
pool:
 vmImage: 'ubuntu-latest'
steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Docker@2
  inputs:
    containerRegistry: 'Dockerhub-registry'
    repository: 'jksoam777/nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: CmdLine@2
  inputs:
    script: 'docker pull jksoam777/nginx:$(Build.BuildId)'
- task: CmdLine@2
  inputs:
    script: |
      sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.2_Linux-64bit.deb
- task: CmdLine@2
  inputs:
    script: 'trivy image --severity CRITICAL,HIGH --exit-code 1 --no-progress jksoam777/nginx:$(Build.BuildId)'