trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonorcloud'           # ✅ Service connection name
    organization: 'jksoam007'          # ✅ Your SonarCloud org
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'your-project-key'  # ✅ Your unique project key from SonarCloud
    cliProjectName: 'your-project-name'
    cliSources: 'src'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
