trigger:
  branches:
   include:
     - main
pool:
 vmImage: 'ubuntu-latest'
   


resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'b10acr'
        repository: 'jksoam'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
