# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: default

steps:
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'service-jk'
    azureResourceGroup: 'jksoam'
    kubernetesCluster: 'jkcluster'
    manifests: 'Manifests/*'

