trigger:
 branches:
    include:
      - main
variables:
  - group: VariableGroupJK
pool:
 vmImage: 'ubuntu-latest'
steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(Password) | docker login $(LoginServer) -u $(Username) --password-stdin'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker build -t $(LoginServer)/myapp:$(Build.BuildId)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker push $(LoginServer)/myapp:$(Build.BuildId)'