apiVersion: apps/v1
kind: Deployment
metadata:
  name: frantnew-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frantnew
  template:
    metadata:
      labels:
        app: frantnew
    spec:
      containers:
      - name: frantnew-container
        image: jksoam777/frantnew:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frantnew-service
spec:
  type: LoadBalancer
  selector:
    app: frantnew
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
