apiVersion: apps/v1
kind: Deployment
metadata:
  name: jksoam777/frantv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jksoam777/frantv
  template:
    metadata:
      labels:
        app: jksoam777/frantv
    spec:
      containers:
      - name: frantnew-container
        image: jksoam777/frantv:v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frantnew-service
spec:
  type: LoadBalancer
  selector:
    app: jksoam777/frantv
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
